version: '3.8'
services:
  server:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mysqldb
  mysqldb:
    platform: linux/x86_64
    image: "mysql:8.2.0"
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: meal_gpt
      MYSQL_USER: joe
      MYSQL_PASSWORD: joe
      MYSQL_ROOT_PASSWORD: joe


